version: 2.1

aliases:

#  SDK cache aliases

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build --stacktrace